<ModuleDefinition
	ModuleId="Cheetah"
	VersionId="1"
	Description="Implementation of a vehicle example using the Cheetah model"
	ScriptFile="Cheetah"
	CreateFunction="onCreate"
	DestroyFunction="onDestroy"
	Group="Game"
    Dependencies="UI=1"
	Priority="1.0">
	<DeclaredAssets
        canSave="true"
        canSaveDynamicFields="true"
        Extension="asset.taml"
        Recurse="true" />
</ModuleDefinition>